# Generated by Django 5.2.4 on 2025-07-23 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adoption', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='breed',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='is_adopted',
        ),
        migrations.AddField(
            model_name='pet',
            name='species',
            field=models.CharField(default='Dog', max_length=50),
        ),
    ]
